DEFAULTS: &DEFAULTS
  dropin: 120
  course_per_class: 80
  support_mail: jonas@navayoga.se
  support_mail_title: Nava Yoga
  support_phone: 0709-961600
  
development:
  host: localhost:3000
  <<: *DEFAULTS

production:
  host: www.naava.se
  <<: *DEFAULTS
