DEFAULTS: &DEFAULTS
  dropin: 130
  course_per_class: 90
  support_mail: jonas@navayoga.se
  support_mail_title: Nava Yoga Studio
  support_phone: 0709-961600
  
development:
  host: localhost:3000
  <<: *DEFAULTS

production:
  host: www.navayoga.se
  <<: *DEFAULTS
